# Generated by Django 2.0.3 on 2019-10-19 13:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='user_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.IntegerField(default=None, null=True, unique=True)),
                ('location_lat', models.DecimalField(blank=True, decimal_places=6, default=None, max_digits=10)),
                ('location_lng', models.DecimalField(blank=True, decimal_places=6, default=None, max_digits=10)),
                ('child_count', models.IntegerField(default=0, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
