# Generated by Django 2.0.3 on 2019-10-28 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connect', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_info',
            name='city',
            field=models.CharField(blank=True, default=None, max_length=250, null=True),
        ),
    ]
